### ISSUE TITLE
[Bug] EditButton is not displayed in NoteUI

### ISSUE THREAD

**Issue by fossamagna** [aws-amplify/learn#394]
**Issue**:

I got following error on browser console and icon to edit note is not shown, when I works on step `Modify AWS Amplify Studio Generated Components in Code`.

Expect the edit icon to appear to the left of the trash icon. But, it not appered.
<img width="339" alt="スクリーンショット 2022-12-02 16 03 32" src="https://user-images.githubusercontent.com/1638848/205236250-90b1ee20-0b4b-4f85-8a3b-2c7570adafaa.png">

```
react-dom.development.js:86 Warning: The tag <path> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    at path
    at button
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36719:20
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36626:18
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36626:18
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36626:18
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36626:18
    at NoteUI (http://localhost:3000/static/js/bundle.js:1701:5)
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36669:18
    at C (http://localhost:3000/static/js/bundle.js:36153:19)
    at div
    at http://localhost:3000/static/js/bundle.js:38032:11
    at http://localhost:3000/static/js/bundle.js:36626:18
    at y (http://localhost:3000/static/js/bundle.js:36170:20)
    at NoteUICollection (http://localhost:3000/static/js/bundle.js:2002:12)
    at div
    at App (http://localhost:3000/static/js/bundle.js:34:96)
    at div
    at $f631663db3294ace$export$c760c09fdd558351 (http://localhost:3000/static/js/bundle.js:73283:10)
    at n (http://localhost:3000/static/js/bundle.js:35421:15)
```

If you delete the following `as 'button'` description, the error will not occur. And the edit icon will also appear.

```jsx
<NoteUICollection overrideItems={({ item, idx }) => {
  return {
    overrides: {
      Vector31472464: {
        as: 'button',
        onClick: () => {
          setShowUpdateModal(true)
          setUpdateNote(item)
        }
      }
    }
  }
}}
/>
```
in https://amplify.aws/learn/courses/Fullstack-for-Frontend-Developers-e7319/lessons/9

I think that the following modification is advisable.
```jsx
<NoteUICollection overrideItems={({ item, idx }) => {
  return {
    overrides: {
      EditButton: {
        onClick: () => {
          setShowUpdateModal(true)
          setUpdateNote(item)
        }
      }
    }
  }
}}
/>

```

**Comment by rubiconjosh** [comment]
I had the same issue and made the same modification to continue the course.
